import type { Metadata } from "next"
import { Inter, Unbounded } from "next/font/google"

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

import "./globals.css"

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter"
})

const unbounded = Unbounded({
	subsets: ["latin"],
	variable: "--font-unbounded"
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
	return (
		<html lang="pt-BR">
			<body className={`${unbounded.className} ${inter.variable} antialiased`}>
				<Header />
				<main className="container mx-auto">{children}</main>
			</body>
		</html>
	)
}

export default RootLayout
